[project]
name = "python-intermediate-inflammation-mha"
version = "0.2.0"
description = "An example software project"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pytest-cov>=7.1.0",
]

[project.urls]
Repo = "https://github.com/martinherrerias/python-intermediate-inflammation"
Course = "https://github.com/carpentries-incubator/python-intermediate-development"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytype>=2024.9.13",
    "pylint>=3.3.9",
    "ruff>=0.15.10",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "UP", "B", "SIM", "RUF", "D", "PL"]
ignore = [
    "D401",  # imperative mood
    "D202",  # no blank lines after docstring
]
[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.pytype]
inputs = ['inflammation']

[tool.pytest.ini_options]
addopts = "--cov-report=term-missing --cov=inflammation"
testpaths = ["tests"]
pythonpath = ["."]

[build-system]
requires = ["uv_build>=0.11.1,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "inflammation"
module-root = ""

[project.scripts]
inflammation = "inflammation.controller:cli"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
